# Generated by Django 3.2.25 on 2025-06-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='fundacion',
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='fecha_fundacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
